# Generated by Django 4.2.23 on 2025-09-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='urlImage',
            field=models.URLField(blank=True, null=1, verbose_name='url image'),
        ),
    ]
